# Generated by Django 3.2.25 on 2024-10-23 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('full_name', models.CharField(max_length=100)),
                ('about', models.TextField(blank=True)),
                ('profession', models.CharField(choices=[('Interior Designer', 'Interior Designer'), ('Architect', 'Architect'), ('Graphic Designer', 'Graphic Designer'), ('Painter', 'Painter')], default='Architect', max_length=50)),
                ('years_of_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('website', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('avatar', models.ImageField(default='../avatar_jyhi5q', upload_to='images/')),
                ('avatar_alt_text', models.CharField(blank=True, default="Users's profile picture", max_length=150)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
