# Generated by Django 3.2.4 on 2024-12-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profession',
            field=models.CharField(choices=[('Interior Designer', 'Interior Designer'), ('Architect', 'Architect'), ('Graphic Designer', 'Graphic Designer'), ('Painter', 'Painter')], max_length=50),
        ),
    ]
